"""Initial schema

Revision ID: 189deed5f8e8
Revises: 
Create Date: 2026-07-04 18:18:16.478948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '189deed5f8e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('split',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('OverviewPage', sa.String(length=255), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('standings',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('LeagueName', sa.String(length=255), nullable=False),
    sa.Column('Team', sa.String(length=255), nullable=False),
    sa.Column('Place', sa.Integer(), nullable=False),
    sa.Column('WinSeries', sa.Integer(), nullable=False),
    sa.Column('LossSeries', sa.Integer(), nullable=False),
    sa.Column('Streak', sa.String(length=5), nullable=False),
    sa.Column('StreakDirection', sa.String(length=10), nullable=False),
    sa.Column('Points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('team',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('TeamName', sa.String(length=255), nullable=False),
    sa.Column('Roles', sa.String(length=255), nullable=False),
    sa.Column('RosterLinks', sa.String(length=255), nullable=False),
    sa.Column('Region', sa.String(length=20), nullable=False),
    sa.Column('Split', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('series',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('SeriesKey', sa.String(length=255), nullable=False),
    sa.Column('SplitKey', sa.String(length=100), nullable=False),
    sa.Column('Team1', sa.String(length=100), nullable=False),
    sa.Column('Team1Score', sa.Integer(), nullable=False),
    sa.Column('Team2', sa.String(length=100), nullable=False),
    sa.Column('Team2Score', sa.Integer(), nullable=False),
    sa.Column('Winner', sa.String(length=100), nullable=False),
    sa.Column('Date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('IsInternational', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['SplitKey'], ['split.Name'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('SeriesKey')
    )
    op.create_table('match_data',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('SeriesKey', sa.String(length=255), nullable=False),
    sa.Column('GameNumber', sa.Integer(), nullable=False),
    sa.Column('GameId', sa.String(length=255), nullable=False),
    sa.Column('OverviewPage', sa.String(length=255), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('MatchId', sa.String(length=255), nullable=False),
    sa.Column('WinTeam', sa.String(length=255), nullable=False),
    sa.Column('Winner', sa.String(length=255), nullable=False),
    sa.Column('Team1', sa.String(length=255), nullable=False),
    sa.Column('Team1Bans', sa.String(length=255), nullable=False),
    sa.Column('Team1Picks', sa.String(length=255), nullable=False),
    sa.Column('Team1Score', sa.Integer(), nullable=False),
    sa.Column('Team1Dragons', sa.Integer(), nullable=False),
    sa.Column('Team2Dragons', sa.Integer(), nullable=False),
    sa.Column('Team1Barons', sa.Integer(), nullable=False),
    sa.Column('Team2Barons', sa.Integer(), nullable=False),
    sa.Column('Team1VoidGrubs', sa.Integer(), nullable=False),
    sa.Column('Team2VoidGrubs', sa.Integer(), nullable=False),
    sa.Column('Team1Towers', sa.Integer(), nullable=False),
    sa.Column('Team2Towers', sa.Integer(), nullable=False),
    sa.Column('Team1RiftHeralds', sa.Integer(), nullable=False),
    sa.Column('Team2RiftHeralds', sa.Integer(), nullable=False),
    sa.Column('Team1Gold', sa.Integer(), nullable=False),
    sa.Column('Team2Gold', sa.Integer(), nullable=False),
    sa.Column('Team2', sa.String(length=255), nullable=False),
    sa.Column('Team2Bans', sa.String(length=255), nullable=False),
    sa.Column('Team2Picks', sa.String(length=255), nullable=False),
    sa.Column('Team2Score', sa.Integer(), nullable=False),
    sa.Column('Split', sa.String(length=255), nullable=False),
    sa.Column('Patch', sa.String(length=255), nullable=False),
    sa.Column('Vod', sa.String(length=255), nullable=False),
    sa.Column('GameLength', sa.String(length=100), nullable=False),
    sa.Column('Date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('IsInternational', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['SeriesKey'], ['series.SeriesKey'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('GameId')
    )
    op.create_table('game_data',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('MatchId', sa.String(length=255), nullable=False),
    sa.Column('GameId', sa.String(length=255), nullable=False),
    sa.Column('Team', sa.String(length=255), nullable=False),
    sa.Column('Side', sa.String(length=30), nullable=False),
    sa.Column('Role', sa.String(length=30), nullable=False),
    sa.Column('PlayerWin', sa.String(length=5), nullable=False),
    sa.Column('Champion', sa.String(length=20), nullable=False),
    sa.Column('Items', sa.String(length=255), nullable=False),
    sa.Column('Trinket', sa.String(length=255), nullable=False),
    sa.Column('Kills', sa.Integer(), nullable=False),
    sa.Column('Deaths', sa.Integer(), nullable=False),
    sa.Column('Assists', sa.Integer(), nullable=False),
    sa.Column('Gold', sa.Integer(), nullable=False),
    sa.Column('CS', sa.Integer(), nullable=False),
    sa.Column('VisionScore', sa.Integer(), nullable=False),
    sa.Column('SummonerSpells', sa.String(length=255), nullable=False),
    sa.Column('Runes', sa.String(length=255), nullable=False),
    sa.Column('DamageToChampions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['GameId'], ['match_data.GameId'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_data')
    op.drop_table('match_data')
    op.drop_table('series')
    op.drop_table('team')
    op.drop_table('standings')
    op.drop_table('split')
    # ### end Alembic commands ###
